### ISSUE TITLE
Hi I have a problem

### ISSUE THREAD

**Issue by muhommadalmusawi** [UltimateHackers/infinity#2]
Hi I have a problem
-----------------------

←[1;34m[?]←[1;m Enter the country code: 964
←[1;34m[?]←[1;m Enter the magic sum: 34
Traceback (most recent call last):
  File "C:\Users\AL-Musawi\Desktop\infinity.py", line 117, in <module>
    limits(count)
  File "C:\Users\AL-Musawi\Desktop\infinity.py", line 59, in limits
    return int(''.join(limit))
ValueError: invalid literal for int() with base 10: ''

**Comment by UltimateHackers** [comment]
You must replace the unknown digits with x like 9825xxxx09
